version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - logging-net


#  backend:
#    build:
#      context: ./backend
#    ports:
#      - "50051:50051"
#    depends_on:
#      - elasticsearch


#  dashboard:
#    build:
#      context: ./dashboard
#    ports:
#      - "3000:3000"
#    environment:
#      - REACT_APP_API_URL=http://backend:50051

networks:
  logging-net:
    driver: bridge
